kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: konflux-ci-maintainers
  namespace: konflux-ci
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: konflux-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: component-maintainer
