apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup-toolchain-host
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schedule: 30 1,13 * * * # every day 1:30, 13:30 UTC
  template:
    includedNamespaces:
      - toolchain-host-operator
    storageLocation: velero-aws-1
    ttl: 720h0m0s
  useOwnerReferencesInBackup: true
