apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ci-helper-app
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              selector:
                matchLabels:
                  appstudio.redhat.com/ci-helper-app: "true"
              values:
                sourceRoot: components/ci-helper-app
                environment: staging
                clusterDir: ""
          - list:
              elements: []
  template:
    metadata:
      name: ci-helper-app-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: ci-helper-app
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m