apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-stage-redhat-io-pull-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        key: production/qe/registry-stage-redhat-io-pull-secret
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: registry-stage-redhat-io-pull-secret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      metadata:
        labels:
          mintmaker.appstudio.redhat.com/secret-type: registry
      data:
        .dockerconfigjson: "{{ .config }}"
