---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: openshift-provider
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.rhtap: tba
---
kind: Secret
apiVersion: v1
metadata:
  name: openshift-provider
  annotations:
    kubernetes.io/service-account.name: openshift-provider
type: kubernetes.io/service-account-token
---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  external:
    enabled: false
  externalAccess:
    enabled: true
  instances: 3
  keycloakDeploymentSpec:
    imagePullPolicy: Always
  multiAvailablityZones:
    enabled: true
  postgresDeploymentSpec:
    imagePullPolicy: Always
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: redhat-external
  labels:
    realm: redhat-external
    app: sso
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    clientScopes:
      - name: first-and-last-name
        protocol: openid-connect
        protocolMappers:
          - name: first_name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            config:
              user.attribute: firstName
              claim.name: first_name
              jsonType.label: String
              id.token.claim: 'true'
              access.token.claim: 'true'
              lightweight.claim: 'false'
              userinfo.token.claim: 'true'
              introspection.token.claim: 'true'
          - name: last_name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            config:
              user.attribute: lastName
              claim.name: last_name
              jsonType.label: String
              id.token.claim: 'true'
              access.token.claim: 'true'
              lightweight.claim: 'false'
              userinfo.token.claim: 'true'
              introspection.token.claim: 'true'
      - attributes:
          display.on.consent.screen: 'true'
          include.in.token.scope: 'true'
        id: 672455b2-1e92-44f6-9fb6-fe2017995aed
        name: profile_level.name_and_dev_terms
        protocol: openid-connect
      - id: 65c7d0bd-243d-42d2-b7f2-64ce2fa7ca7e
        name: profile
        description: 'OpenID Connect built-in scope: profile'
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
          consent.screen.text: ${profileScopeConsentText}
        protocolMappers:
          - id: e3f5a475-0722-4293-bcd5-2bad6bc7dde6
            name: locale
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: locale
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: locale
              jsonType.label: String
          - id: 7b91d2ec-3c9f-4e7d-859e-67900de0c6b6
            name: full name
            protocol: openid-connect
            protocolMapper: oidc-full-name-mapper
            consentRequired: false
            config:
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
          - id: d301c7b7-0d97-4d37-8527-a5c63d461a3c
            name: family name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: lastName
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: family_name
              jsonType.label: String
          - id: 71c6caff-3f17-47db-8dc1-42f9af01832e
            name: updated at
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: updatedAt
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: updated_at
              jsonType.label: long
          - id: 6bcb9f8d-94be-48b3-bd47-2ba7746d65ac
            name: picture
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: picture
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: picture
              jsonType.label: String
          - id: d497ef2e-5d5b-4d8a-9392-04e09f5c51b6
            name: nickname
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: nickname
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: nickname
              jsonType.label: String
          - id: f8167604-073d-47ea-9fd1-6ec754ce5c49
            name: website
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: website
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: website
              jsonType.label: String
          - id: 48d8f2ff-d0e6-41f2-839e-3e51951ee078
            name: profile
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: profile
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: profile
              jsonType.label: String
          - id: 463f80df-1554-4f0b-889f-1e6f2308ba17
            name: username
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: username
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: preferred_username
              jsonType.label: String
          - id: c347cd4f-a2e1-4a5f-a676-e779beb7bccf
            name: given name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: firstName
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: given_name
              jsonType.label: String
          - id: 665672fd-872e-4a58-b586-b6f6fddbc1ac
            name: zoneinfo
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: zoneinfo
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: zoneinfo
              jsonType.label: String
          - id: b76e46cc-98a9-4bf7-8918-0cc8eb2dfc8c
            name: gender
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: gender
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: gender
              jsonType.label: String
          - id: cb1a55e3-87f0-4efb-b5c0-d5de40344bfc
            name: birthdate
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: birthdate
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: birthdate
              jsonType.label: String
          - id: 9b5c1c92-c937-4216-9fdb-db23d6eee788
            name: middle name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: middleName
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: middle_name
              jsonType.label: String
      - id: 45e1900d-2199-45fc-9028-a39497a6cdd5
        name: email
        description: 'OpenID Connect built-in scope: email'
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
          consent.screen.text: ${emailScopeConsentText}
        protocolMappers:
          - id: 149315f5-4595-4794-b11f-f4b68b1c9f7a
            name: email
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: email
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: email
              jsonType.label: String
          - id: 26f0791c-93cf-4241-9c92-5528e67b9817
            name: email verified
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: emailVerified
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: email_verified
              jsonType.label: boolean
    displayName: redhat-external
    enabled: true
    id: redhat-external
    identityProviders:
      - alias: openshift-v4
        config:
          authorizationUrl: >-
            https://oauth.stone-stage-p01.apys.p3.openshiftapps.com/oauth/authorize
          baseUrl: 'https://api.stone-stage-p01.apys.p3.openshiftapps.com:443'
          clientId: 'system:serviceaccount:rhtap-auth:openshift-provider'
          clientSecret: "To be added manually in the keycloak UI see the readme"
          tokenUrl: 'https://oauth.stone-stage-p01.apys.p3.openshiftapps.com/oauth/token'
          syncMode: "FORCE"
        enabled: true
        internalId: openshift-v4
        providerId: openshift-v4
    realm: redhat-external
    sslRequired: all
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: cloud-services
  labels:
    app: sso
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  client:
    enabled: true
    clientAuthenticatorType: client-secret
    redirectUris:
      - '*'
    clientId: cloud-services
    optionalClientScopes:
      - address
      - phone
      - profile_level.name_and_dev_terms
      - offline_access
      - microprofile-jwt
    defaultClientScopes:
      - web-origins
      - acr
      - nameandterms
      - profile
      - roles
      - email
      - first-and-last-name
    implicitFlowEnabled: false
    secret: client-secret
    publicClient: true
    standardFlowEnabled: true
    webOrigins:
      - '*'
    id: e3e1d703-62c1-46f4-b706-e3d7eebafd01
    directAccessGrantsEnabled: false
  realmSelector:
    matchLabels:
      realm: redhat-external
  scopeMappings: {}
