---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  channel: stable
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: keycloak-operatorgroup
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  targetNamespaces:
    - rhtap-auth
