---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-service-gitops-component-maintainers
  namespace: gitops
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: konflux-gitops-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-component-maintainer
