apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: reduce-replicas.yaml
    target:
      group: keycloak.org
      version: v1alpha1
      name: keycloak
      kind: Keycloak
  - path: set-redirect-uri.yaml
    target:
      name: openshift-provider
      kind: ServiceAccount
  - path: set-ocp-idp.yaml
    target:
      name: redhat-external
      kind: KeycloakRealm
