apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tracing
  namespace: openshift-pipelines
data:
  enabled: "true"
  endpoint: "http://open-telemetry-opentelemetry-collector.konflux-otel.svc.cluster.local:4318/v1/traces"