apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprayproxy
  namespace: sprayproxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sprayproxy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sprayproxy
                topologyKey: kubernetes.io/hostname
