apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubesaw-common
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/sandbox/common
                environment: staging
                clusterDir: ""
          - list:
              elements: []
  template:
    metadata:
      name: kubesaw-common-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: ksaw-common
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
