apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac
- https://github.com/konflux-ci/ci-helper-app/deploy/base?ref=c74e02a133e09ed7cbb628919aaaa5cd3325375d


images:
- name: quay.io/konflux-ci/ci-helper-app
  newName: quay.io/konflux-ci/ci-helper-app
  newTag: c74e02a133e09ed7cbb628919aaaa5cd3325375d

namespace: ci-helper-app