apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - power-monitoring-operator.yaml
  - kepler.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
