---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: webhook-config-patch.yaml
    target:
      name: build-service-controller-manager
      kind: Deployment
namespace: build-service
