apiVersion: template.openshift.io/v1
kind: Template
metadata: {}
objects:
- apiVersion: toolchain.dev.openshift.com/v1alpha1
  kind: Idler
  metadata:
    name: ${SPACE_NAME}-eaas
  spec:
    timeoutSeconds: ${{IDLER_TIMEOUT_SECONDS}}

parameters:
- name: SPACE_NAME
  required: true
- name: IDLER_TIMEOUT_SECONDS
  # No Idling
  value: "0"
