apiVersion: template.openshift.io/v1
kind: Template
metadata: {}
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      openshift.io/description: ${SPACE_NAME}
      openshift.io/display-name: ${SPACE_NAME}
      openshift.io/requester: ${SPACE_NAME}
    labels:
      name: ${SPACE_NAME}-eaas
    name: ${SPACE_NAME}-eaas

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: ${SPACE_NAME}-eaas
    name: namespace-manager

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: cluster-provisioner-rb
    namespace: ${SPACE_NAME}-eaas
  subjects:
  - kind: ServiceAccount
    name: namespace-manager
    namespace: ${SPACE_NAME}-eaas
  roleRef:
    kind: ClusterRole
    name: cluster-provisioner
    apiGroup: rbac.authorization.k8s.io

- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: quota
    namespace: ${SPACE_NAME}-eaas
  spec:
    hard:
      # compute
      limits.cpu: "0"
      limits.memory: "0"
      requests.cpu: "0"
      requests.memory: "0"
      # storage
      requests.storage: "0"
      limits.ephemeral-storage: "0"
      requests.ephemeral-storage: "0"
      # disallowed resource counts
      count/configmaps: "0"
      count/cronjobs: "0"
      count/deployments.apps: "0"
      count/jobs: "0"
      count/persistentvolumeclaims: "0"
      count/pods: "0"
      count/replicasets.apps: "0"
      count/replicationcontrollers: "0"
      count/routes: "0"
      count/services: "0"
      count/statefulsets.apps: "0"
      # allowed resource counts
      count/clustertemplateinstances.clustertemplate.openshift.io: "5"
      count/secrets: "100"

parameters:
- name: SPACE_NAME
  required: true
