apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: konflux-eaas-tier
objects:
- kind: NSTemplateTier
  apiVersion: toolchain.dev.openshift.com/v1alpha1
  metadata:
    name: konflux-eaas
    namespace: ${NAMESPACE}
  spec:
    clusterResources:
      templateRef: ${CLUSTER_TEMPL_REF}
    namespaces:
    - templateRef: ${EAAS_TEMPL_REF}
    spaceRoles:
      admin:
        templateRef: ${ADMIN_TEMPL_REF}
      maintainer:
        templateRef: ${MAINTAINER_TEMPL_REF}
      contributor:
        templateRef: ${CONTRIBUTOR_TEMPL_REF}
      viewer:
        templateRef: ${VIEWER_TEMPL_REF}
    spaceRequestConfig:
      serviceAccountName: namespace-manager
parameters:
- name: NAMESPACE
- name: CLUSTER_TEMPL_REF
- name: EAAS_TEMPL_REF
- name: ADMIN_TEMPL_REF
- name: MAINTAINER_TEMPL_REF
- name: CONTRIBUTOR_TEMPL_REF
- name: VIEWER_TEMPL_REF
