apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - https://github.com/redhat-appstudio/remote-secret/config/overlays/openshift_vault?ref=fd4c134f2965bfb617cc9ca9b5f09a4d7663ff23

namespace: remotesecret

images:
  - name:  quay.io/redhat-appstudio/remote-secret-controller
    newName: quay.io/redhat-appstudio/remote-secret-controller
    newTag: 1f1a541eb25c3237715e3a67a90c8f0029142bfa

patches:
  - target:
      kind: ConfigMap
      name: remote-secret-controller-manager-environment-config
    path: config-patch.json
