apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ca-bundle
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/ca-bundle
                environment: staging
                clusterDir: ""
              selector:
                matchLabels:
                  appstudio.redhat.com/internal-member-cluster: "true"
          - list:
              elements: []
  template:
    metadata:
      name: ca-bundle-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/internal-infra-deployments.git
        targetRevision: main
      destination:
        namespace: openshift-config
        server: '{{server}}'
      syncPolicy:
        automated:
          # prune is false because of https://github.com/argoproj/argo-cd/issues/5792
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
