kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: has-admin
  namespace: application-service
rules:
  - verbs:
      - get
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - "patch"
    apiGroups:
      - "apps"
    resources:
      - "deployments/scale"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: has-admin
  namespace: application-service
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: konflux-has
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: has-admin
