---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops
$patch: delete
---
# Tempo is excluded from the staging
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tempo
$patch: delete
