---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: add-rh-certs-patch.yaml
    target:
      name: mintmaker-controller-manager
      kind: Deployment
configMapGenerator:
  - name: trusted-ca
    options:
      labels:
        "config.openshift.io/inject-trusted-cabundle": "true"
namespace: mintmaker
