apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-provider: codeready-toolchain
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  name: dev-sandbox-host
  namespace: toolchain-host-operator
spec:
  displayName: Dev Sandbox Operators
  image: quay.io/codeready-toolchain/host-operator-index:latest
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 5m0s
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dev-sandbox-host
  namespace: toolchain-host-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  targetNamespaces:
  - toolchain-host-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dev-sandbox-host
  namespace: toolchain-host-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  channel: staging
  installPlanApproval: Automatic
  name: toolchain-host-operator
  source: dev-sandbox-host
  sourceNamespace: toolchain-host-operator
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-olm
  namespace: toolchain-host-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  podSelector:
    matchLabels:
      olm.catalogSource: dev-sandbox-host
  ingress:
    - ports:
        - protocol: TCP
          port: 50051
      from:
        - podSelector: {}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-operator-lifecycle-manager
  policyTypes:
    - Ingress
