---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-allow-team-access-to-jgwest-tenant
  namespace: jgwest-tenant
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: konflux-gitops-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-namespaces-all-access
---
