apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/keycloak
                environment: staging
                clusterDir: ""
              selector:
                matchLabels:
                  appstudio.redhat.com/internal-member-cluster: "true"
          - list:
              elements:
                - nameNormalized: stone-stage-p01
                  values.clusterDir: stone-stage-p01
                - nameNormalized: stone-prod-p01
                  values.clusterDir: stone-prod-p01
                - nameNormalized: stone-prod-p02
                  values.clusterDir: stone-prod-p02
  template:
    metadata:
      name: keycloak-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: rhtap-auth
        server: '{{server}}'
      ignoreDifferences:
        - group: keycloak.org
          kind: KeycloakRealm
          jsonPointers:
            - /spec/realm/identityProviders/0/config/clientSecret
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
