apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: konflux-public-staging
patches:
  - target:
      kind: Application
      name: all-application-sets
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: konflux-public-staging
