kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-controller-maintainers
  namespace: project-controller
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: konflux-o11y
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: project-controller-maintainer
