apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tempo-operator.yaml
  - tempo.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
